name: "Pull Request Reviewer"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != "modular-magician"
    steps:
    - uses: actions/checkout@v2
    - uses: uesteibar/reviewer-lottery@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
